### ISSUE TITLE
Getting "An error occurred whilst attempting to rehydrate code-split-component"

### ISSUE THREAD

**Issue by andreyluiz** [ctrlplusb/code-split-component#31]
Hello. First congratulation for this amazing library.

I am getting this error in the production build with SSR.

The full strack trace:

```
An error occurred whilst attempting to rehydrate code-split-component. TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (http://localhost:8000/vendor.4236bf86234939fda7e5.js:51:29)
    at resolveModule (http://localhost:8000/vendor.4236bf86234939fda7e5.js:28709:38)
    at Array.map (native)
    at http://localhost:8000/vendor.4236bf86234939fda7e5.js:28714:23 TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (http://localhost:8000/vendor.4236bf86234939fda7e5.js:51:29)
    at resolveModule (http://localhost:8000/vendor.4236bf86234939fda7e5.js:28709:38)
    at Array.map (native)
    at http://localhost:8000/vendor.4236bf86234939fda7e5.js:28714:23
```

It appears to be something related to the JSONp request.

My code:

**Root.js**
```jsx
import React from 'react';
import { Match } from 'react-router';
import { CodeSplit } from 'code-split-component';

const Root = () => (
  <div className="container">
    <h1>Welcome to App</h1>

    <Match
      exactly
      pattern="/"
      render={routerProps =>
        <CodeSplit chunkName="index" modules={{ Index: require('./Index') }}>
          { ({ Index }) => Index && <Index {...routerProps} /> }
        </CodeSplit>}
    />
  </div>
);

export default Root;

```

**.babelrc**
```
{
  "presets": ["es2015", "stage-3", "react"],
  "env": {
    "development": {
      "plugins": [
        ["code-split-component/babel", {
          "disabled": true
        }],
        "react-hot-loader/babel"
      ]
    },
    "production": {
      "plugins": [
        "code-split-component/babel"
      ]
    }
  }
}
```

**webpack.config.server.js**
```javascript
[...]
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel',
        query: {
          presets: [
            'react',
            'es2015',
            'stage-0',
          ],
          plugins: [
            [
              'babel-plugin-webpack-loaders',
              { config: './webpack.config.babel.js', verbose: false }
            ],
            [
              'code-split-component/babel',
              { mode: 'server' }
            ]
          ]
        },
      },
[...]
```

**webpack.config.prod.js**

```javascript
[...]

  plugins: [
    new ManifestPlugin(),
    new CodeSplitWebpackPlugin(),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      minChunks: Infinity,
      filename: '[name].[chunkhash].js',
    }),
  ]
```

**server.js**

```jsx
  const codeSplitContext = createRenderContext();

  const content = renderToString(
    <CodeSplitProvider context={codeSplitContext}>
      <ServerRouter location={req.url} context={reactRouterContext}>
        <Root />
      </ServerRouter>
    </CodeSplitProvider>,
  );
```

**client.js**

```jsx
function renderApp(TheApp) {
  rehydrateState().then(codeSplitState =>
    render(
      <ReactHotLoader>
        <CodeSplitProvider state={codeSplitState}>
          <BrowserRouter>
            <TheApp />
          </BrowserRouter>
        </CodeSplitProvider>
      </ReactHotLoader>,
    mountNode),
  );
}
```

**package.json dependencies**

```json
"dependencies": {
    "babel-plugin-add-module-exports": "^0.2.1",
    "bootstrap-sass": "^3.3.7",
    "code-split-component": "2.0.0-alpha.5",
    "express": "^4.14.0",
    "extract-text-webpack-plugin": "^1.0.1",
    "json-loader": "^0.5.4",
    "react": "^15.4.2",
    "react-bootstrap": "^0.30.7",
    "react-dom": "^15.4.2",
    "react-router": "4.0.0-alpha.6",
    "serialize-javascript": "^1.3.0",
    "webpack-vendor-chunk-plugin": "^1.0.0"
  },
  "devDependencies": {
    "babel-cli": "^6.18.0",
    "babel-core": "^6.21.0",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.2.10",
    "babel-plugin-webpack-loaders": "^0.8.0",
    "babel-preset-env": "^1.1.8",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-3": "^6.17.0",
    "chunk-manifest-webpack-plugin": "^1.0.0",
    "cross-env": "^3.1.4",
    "css-loader": "^0.26.1",
    "cssnano": "^3.10.0",
    "empty": "^0.10.1",
    "eslint": "^3.13.1",
    "eslint-config-airbnb": "^14.0.0",
    "eslint-plugin-flowtype": "^2.30.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^3.0.2",
    "eslint-plugin-react": "^6.9.0",
    "file-loader": "^0.9.0",
    "flow-bin": "^0.37.4",
    "node-sass": "^4.3.0",
    "postcss-cssnext": "^2.9.0",
    "postcss-focus": "^1.0.0",
    "postcss-loader": "^1.2.2",
    "postcss-reporter": "^3.0.0",
    "react-hot-loader": "^3.0.0-beta.2",
    "rimraf": "^2.5.4",
    "sass-loader": "^4.1.1",
    "sass-resources-loader": "^1.2.0-beta.1",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^1.14.0",
    "webpack-dev-middleware": "^1.9.0",
    "webpack-externals-plugin": "^1.0.0",
    "webpack-hot-middleware": "^2.15.0",
    "webpack-manifest-plugin": "^1.1.0"
  }
```

I wrote this very quickly, so if you need more information, just ask me.

I really want to use this component. It helps a lot.

Thank you.

**Comment by ctrlplusb** [comment]
Hi @andreyluiz !

Thanks for the kind words and the detailed bug report. I will take a look at it when I can. In the interim I would recommend that you look at my new [`react-async-component`](https://github.com/ctrlplusb/react-async-component). It has less magic in it so should be far less likely to experience these types of issues. 

Let me know your experience if you do try it out.

**Comment by andreyluiz** [comment]
OMG! You're awesome. I'll give it a try, then I come back and report. Thank you very much for your support. :D

**Comment by ctrlplusb** [comment]
No worries, just be aware that it doesn't support React Hot Loader at the moment. You can still use Webpack's hot module replacement, just not React Hot Loader.

**Comment by andreyluiz** [comment]
Yeah, I figured it out in the documentation. For development I'm not using code splitting. In production it splits correctly (in the build), but this error occurs in run-time.

Okay, about the `react-async-component`, I completely removed the `code-split-component` and implemented over the `Root.js` with the suggested library aaaand... success! :tada: :tada: 

The implementation is ridiculously more simple and it works like a charm. The example above shows how I implemented it:

```jsx
import React from 'react';
import { Match } from 'react-router';
import { createAsyncComponent } from 'react-async-component';

const AsyncIndex = createAsyncComponent({
  resolve: () => new Promise(resolve =>
    require.ensure([], (require) => {
      resolve(require('./Index'));
    }),
  ),
});

const Root = () => (
  <div className="container">
    <h1>Welcome to App</h1>

    <Match
      exactly
      pattern="/"
      render={routerProps =>
        <AsyncIndex {...routerProps} />}
    />
  </div>
);

export default Root;
```

The chunks appear in development and production and in run-time they are loaded successfully. The only thing I do not know how to do is how to name the chunks properly. In my webpack config I have the `output.chunkFilename` with the value `[name].[chunkhash].js`. But the chunks are generating `1.[hash].js, 2.[hash].js`. Do you know how can I change the name from 1 to another name?

**Comment by ctrlplusb** [comment]
Hi @andreyluiz thanks for the feedback!

> The only thing I do not know how to do is how to name the chunks properly.

Sure thing, if you want chunk names then use Webpack's `require.ensure` API which gives you this capability.  For example:

```js
const AsyncIndex = createAsyncComponent({
  resolve: () => new Promise(resolve => require.ensure([], 
    require => resolve(require('./Index')),
    'ChunkNameHere'
  ))
});

<AsyncIndex />
```

Just replace `'ChunkNameHere'` with whatever you would like to name your chunk as. 🙏

----

In terms of your implementation, I have a few recommendations.  Firstly, in regards to your `Match` component implementation, you can simplify this now to be the following:

```jsx
const Root = () => (
  <div className="container">
    <h1>Welcome to App</h1>
    <Match exactly pattern="/" component={AsyncIndex} />
  </div>
);
```

Much cleaner now! 🎉 
Another advantage of the new API.

And then I recommend that you structure your components in the following folder/file structure (I have renamed your `Index` component to `Home` to avoid some confusion in the naming here):

```
 |- AsyncHome
    |- index.js
    |- Home.js
```

Then the files could have the following contents:

__AsyncHome/index.js__

```js
const AsyncHome = createAsyncComponent({
  resolve: () => new Promise(resolve => require.ensure([], 
    require => resolve(require('./Home')),
    'home'
  ))
});

export default AsyncHome;
```

__AsyncHome/Home.js__

```jsx
import React from 'react';

export default function Home() {
  return <h1>Hello World!</h1>;
}
```

Now, you can simply import `AsyncHome` anywhere in your application and not have to worry about setting up or breaking the async API you wanted it to have.  e.g. your new full app code will be:

```jsx
import React from 'react';
import { Match } from 'react-router';
import AsyncHome from './AsyncHome';

const Root = () => (
  <div className="container">
    <h1>Welcome to App</h1>

    <Match exactly pattern="/" component={AsyncHome} />
  </div>
);

export default Root;
```

🎉

---

Okay, final bit of advice.  If you don't expect your `AsyncHome` to have any children that are async/code-splitting then set the `ssrMode='boundary'` configuration property.  See the docs for more details on this. But basically it tells our helpers that they don't need to search the nested children of `AsyncHome` for any other asynchronous components.  This is a nice little optimisation that can be done, especially if you just do code splitting at the route level which lives at the base of your application.

e.g.

```js
const AsyncHome = createAsyncComponent({
  resolve: () => new Promise(resolve => require.ensure([], 
    require => resolve(require('./Home')),
    'home'
  )),
  ssrMode: 'boundary' // 👈
});

export default AsyncHome;
```

**Comment by andreyluiz** [comment]
Wow! Very nice recommendations. Thank you again, my friend. :D

**Comment by ctrlplusb** [comment]
Project has been deprecated. 💖

**Comment by andreyluiz** [comment]
Nice! Thank you for the help. :)
